### ISSUE TITLE
"under development" error is thrown while importing the interface_create recipe from the Chef-Server 

### ISSUE THREAD

**Issue by Jainpriyal** [Juniper/ruby-junos-ez-stdlib#20]
[root@router recipes]# cat interface_create.rb 
netdev_interface "ge-1/1/1" do
description "access interface"
speed "40g"
action :create
end

netdev_interface "ge-0/0/2" do
description "access interface ge-0/0/2 created"
speed "1g"
duplex "full"
enable false
action :create
end

netdev_interface "ge-0/0/1" do
description "access interface ge-0/0/1 created"
speed "100m"
duplex "half"
action :create
end

root@router % /opt/sdk/chef/bin/ruby /opt/sdk/chef/bin/chef-client -c /config/chef/client.rb
[2015-06-08T06:34:35+05:30] INFO: Forking chef instance to converge...
Starting Chef Client, version 11.10.4
[2015-06-08T06:34:35+05:30] INFO: *** Chef 11.10.4 ***
[2015-06-08T06:34:35+05:30] INFO: Chef-client pid: 26277
[2015-06-08T06:34:37+05:30] INFO: Run List is [recipe[netdev::interface_create]]
[2015-06-08T06:34:37+05:30] INFO: Run List expands to [netdev::interface_create]
[2015-06-08T06:34:37+05:30] INFO: Starting Chef Run for csi-irtb2-b
[2015-06-08T06:34:37+05:30] INFO: Running start handlers
[2015-06-08T06:34:37+05:30] INFO: Start handlers complete.
[2015-06-08T06:34:37+05:30] INFO: HTTP Request Returned 404 Object Not Found: 
resolving cookbooks for run list: ["netdev::interface_create"]
[2015-06-08T06:34:37+05:30] INFO: Loading cookbooks [netdev]
Synchronizing Cookbooks:
  - netdev
Compiling Cookbooks...
/var/chef/cache/cookbooks/netdev/libraries/_junos_api_client.rb:35: warning: already initialized constant KNOWN_RESOURCES
/var/chef/cache/cookbooks/netdev/libraries/_junos_api_client.rb:55: warning: already initialized constant L1ports
/var/chef/cache/cookbooks/netdev/libraries/_junos_api_client.rb:55: warning: already initialized constant L2ports
/var/chef/cache/cookbooks/netdev/libraries/_junos_api_client.rb:55: warning: already initialized constant IPports
/var/chef/cache/cookbooks/netdev/libraries/_junos_api_client.rb:55: warning: already initialized constant Vlans
/var/chef/cache/cookbooks/netdev/libraries/_junos_api_client.rb:55: warning: already initialized constant LAGports
/var/chef/cache/cookbooks/netdev/libraries/_junos_api_client.rb:65: warning: already initialized constant VALUES_TO_SYMBOLIZE
Converging 3 resources
Recipe: netdev::interface_create
  * netdev_interface[ge-1/1/1] action create[2015-06-08T06:34:38+05:30] INFO: Processing netdev_interface[ge-1/1/1] action create (netdev::interface_create line 1)
[2015-06-08T06:34:39+05:30] INFO: Netconf session is sucess

=============================================================================
Error executing action `create` on resource 'netdev_interface[ge-1/1/1]'
=============================================================================

ArgumentError
-------------
under development

Cookbook Trace:
---------------
/var/chef/cache/cookbooks/netdev/libraries/_junos_api_transport.rb:99:in `block in open_connection!'
/var/chef/cache/cookbooks/netdev/libraries/_junos_api_transport.rb:98:in `each_pair'
/var/chef/cache/cookbooks/netdev/libraries/_junos_api_transport.rb:98:in `open_connection!'
/var/chef/cache/cookbooks/netdev/libraries/_junos_api_transport.rb:59:in `initialize'
/var/chef/cache/cookbooks/netdev/libraries/_junos_api_client.rb:161:in `transport'
/var/chef/cache/cookbooks/netdev/libraries/_junos_api_client.rb:147:in `managed_resource'
/var/chef/cache/cookbooks/netdev/libraries/provider_interface_junos.rb:47:in `load_current_resource'

Resource Declaration:
---------------------
# In /var/chef/cache/cookbooks/netdev/recipes/interface_create.rb

  1: netdev_interface "ge-1/1/1" do
  2: description "access interface"
  3: speed "40g"
  4: action :create
  5: end
  6:

**Comment by Jainpriyal** [comment]
this error is coming because of missing "bridge_domain.rb" for l2_interface.

**Comment by Jainpriyal** [comment]
Fixed
