### ISSUE TITLE
Error in rerunning netdev_lag interface 

### ISSUE THREAD

**Issue by Jainpriyal** [Juniper/ruby-junos-ez-stdlib#30]
ADD RECIPE TO THE RUN_LIST:
---------------------------
[root@chef-ws cookbooks]# knife node show tot-mx-k 
Node Name:   node
Environment: _default
FQDN:        
IP:          
Run List:    recipe[netdev::karthi_interface_create], recipe[netdev::karthi_vlan_create], recipe[netdev::karthi_l2interface_create], recipe[netdev::karthi_uplinkinterface_create]
Roles:       
Recipes:     netdev::karthi_interface_create, netdev::karthi_vlan_create, netdev::karthi_l2interface_create, netdev::karthi_uplinkinterface_create

[root@chef-ws1 recipes]# cat karthi_vlan_create.rb 
netdev_vlan "blue" do
        vlan_id 100
        description "Chef Created blue VLAN"
        action :create
end

netdev_vlan "green" do
        vlan_id 200
        description "Chef Created green VLAN"
        action :create
end

netdev_vlan "red" do
        vlan_id 300
        description "Chef Created red VLAN"
        action :create
end
[root@chef-ws1 recipes]# cat karthi_l2interface_create.rb 
netdev_l2_interface "ge-1/0/1" do
        description "belongs to blue VLAN"
        untagged_vlan "blue"
        vlan_tagging false 
        action :create
end

netdev_l2_interface "ge-1/0/2" do
        description "belongs to green VLAN"
        untagged_vlan "green"
        vlan_tagging false
        action :create
end

netdev_l2_interface "ge-1/0/3" do
        description "belongs to red VLAN"
        untagged_vlan "red"
        vlan_tagging false
        action :create
end
[root@chef-ws1 recipes]# cat karthi_interface_create.rb 
netdev_interface "ge-1/0/1" do
        description "Chef Created Access interface"
        action :create
end

netdev_interface "ge-1/0/2" do
        description "Chef Created Access interface"
        action :create
end

netdev_interface "ge-1/0/3" do
        description "Chef Created Access interface"
        action :create
end
[root@chef-ws1 recipes]# cat karthi_uplinkinterface_create.rb 
netdev_l2_interface "ge-1/0/6" do
  action :delete
end

netdev_l2_interface "ge-1/0/7" do
  action :delete
end

netdev_l2_interface "ge-1/0/8" do
  action :delete
end

netdev_l2_interface "ge-1/0/9" do
  action :delete
end

Create the LAGs

netdev_lag "ae0" do
        links [ "ge-1/0/6", "ge-1/0/7" ]
        minimum_links 1
        lacp "active"
        action :create
end

netdev_lag "ae1" do
        links [ "ge-1/0/8", "ge-1/0/9" ]
        minimum_links 1
        lacp "active"
        action :create
end

 Configure Layer 2 switching on the LAGs. Define the port mode as trunk  
 (vlan_tagging true), with membership in the blue, green, and red VLANs.

netdev_l2_interface "ae0" do
        description "Chef Created Uplink interface"
        tagged_vlans [ "blue", "green", "red" ]
        vlan_tagging true
        action :create
end

netdev_l2_interface "ae1" do
        description "Chef Created Uplink interface"
        tagged_vlans ["blue", "green", "red" ] 
        vlan_tagging true
        action :create
end

JUNOS CLIENT:
----------
regress@tot-mx-k> exit 

root@tot-mx-k% /opt/sdk/chef/bin/ruby /opt/sdk/chef/bin/chef-client -c /config/chef/client.rb
[2015-08-21T18:10:43+05:30] INFO: Forking chef instance to converge...
Starting Chef Client, version 11.10.4
[2015-08-21T18:10:44+05:30] INFO: *** Chef 11.10.4 ***
[2015-08-21T18:10:44+05:30] INFO: Chef-client pid: 10014
[2015-08-21T18:10:48+05:30] INFO: Run List is [recipe[netdev::karthi_interface_create], recipe[netdev::karthi_vlan_create], recipe[netdev::karthi_l2interface_create], recipe[netdev::karthi_uplinkinterface_create]]
[2015-08-21T18:10:48+05:30] INFO: Run List expands to [netdev::karthi_interface_create, netdev::karthi_vlan_create, netdev::karthi_l2interface_create, netdev::karthi_uplinkinterface_create]
[2015-08-21T18:10:48+05:30] INFO: Starting Chef Run for tot-mx-k
[2015-08-21T18:10:48+05:30] INFO: Running start handlers
[2015-08-21T18:10:48+05:30] INFO: Start handlers complete.
[2015-08-21T18:10:48+05:30] INFO: HTTP Request Returned 404 Object Not Found: 
resolving cookbooks for run list: ["netdev::karthi_interface_create", "netdev::karthi_vlan_create", "netdev::karthi_l2interface_create", "netdev::karthi_uplinkinterface_create"]
[2015-08-21T18:10:49+05:30] INFO: Loading cookbooks [netdev]
Synchronizing Cookbooks:
 netdev
Compiling Cookbooks...
 netdev_lag[ae0] action create[2015-08-21T18:11:16+05:30] INFO: Processing netdev_lag[ae0] action create (netdev::karthi_uplinkinterface_create line 19)
Error executing action `create` on resource 'netdev_lag[ae0]'
NoMethodError
undefined method `properties' for nil:NilClass
Cookbook Trace:
/var/chef/cache/cookbooks/netdev/libraries/_junos_api_client.rb:127:in `block in updated_changed_properties'
/var/chef/cache/cookbooks/netdev/libraries/_junos_api_client.rb:121:in `each_pair'
/var/chef/cache/cookbooks/netdev/libraries/_junos_api_client.rb:121:in `updated_changed_properties'
/var/chef/cache/cookbooks/netdev/libraries/provider_lag_junos.rb:73:in `action_create'

Resource Declaration:
In /var/chef/cache/cookbooks/netdev/recipes/karthi_uplinkinterface_create.rb

 19: netdev_lag "ae0" do
 20:         links [ "ge-1/0/6", "ge-1/0/7" ]
 21:         minimum_links 1
 22:         lacp "active"
 23:         action :create
 24: end
 25: 

Compiled Resource:
Declared in /var/chef/cache/cookbooks/netdev/recipes/karthi_uplinkinterface_create.rb:19:in `from_file'

netdev_link_aggregation_group("ae0") do
  action [:create]
  retries 0
  retry_delay 2
  lag_name "ae0"
  lacp "active"
  cookbook_name "netdev"
  recipe_name "karthi_uplinkinterface_create"
  links ["ge-1/0/6", "ge-1/0/7"]
  minimum_links 1
end

[2015-08-21T18:11:17+05:30] INFO: Running queued delayed notifications before re-raising exception

Running handlers:
[2015-08-21T18:11:17+05:30] ERROR: Running exception handlers
[2015-08-21T18:11:17+05:30] INFO: Rolled back pending Junos candidate configuration changes
  - JunosCommitTransactionHandler
Running handlers complete

[2015-08-21T18:11:17+05:30] ERROR: Exception handlers complete
[2015-08-21T18:11:17+05:30] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 3 resources updated in 34.402582009 seconds
[2015-08-21T18:11:17+05:30] ERROR: netdev_lag[ae0] (netdev::karthi_uplinkinterface_create line 19) had an error: NoMethodError: undefined method `properties' for nil:NilClass
[2015-08-21T18:11:17+05:30] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

ISSUE:
-------
Invoke the list of recipes once again and it will throw the error, please don't change the order of recipes

"run_list": [
 "recipe[netdev::karthi_interface_create]",
 "recipe[netdev::karthi_vlan_create]",
 "recipe[netdev::karthi_l2interface_create]",
 "recipe[netdev::karthi_uplinkinterface_create]"

**Comment by Jainpriyal** [comment]
resolved https://github.com/Juniper/ruby-junos-ez-stdlib/pull/31
